language: minimal
git:
  depth: 25
env:
  global:
    - BUILDDIR="$TRAVIS_BUILD_DIR/$TRAVIS_BUILD_ID"
    - CONFIG=release
    - VERA=false
    - TRANSLATIONS=false
    - QMAKE_EXTRA="CONFIG+=tests CONFIG+=silent CONFIG+=ccache CONFIG+=noPch"
    - EARLY_START_DOCKER_PULL_PID=$( if [ $TRAVIS_OS_NAME = 'linux' ] ; then docker pull trikset/linux-builder ; else true ; fi 2>&1 >/dev/null & echo $!)
    - HEARTBEAT=$(while sleep 100; do echo "=====[ $SECONDS seconds, still building... ]====="; done >&2 & echo $! )
    - TRIK_QT="$HOME/TRIK_Qt"
cache:
  timeout: 1000
  apt: true
  ccache: true
  directories:
    - $PYENV_ROOT
    - $TRIK_QT
    - $HOME/.ccache
branches:
  except:
    - /dependabot.*/
matrix:
  fast_finish: true
  allow_failures:
#  - os: linux
#    env: CONFIG=debug VERA=true TRANSLATIONS=true QMAKE_EXTRA="$QMAKE_EXTRA CONFIG+=sanitize_address CONFIG+=sanitize_undefined CONFIG+=sanitizer"
  include:
  - os: linux
    services: docker
    sudo: required
    name: Linux release
    env: QMAKE_EXTRA="$QMAKE_EXTRA CONFIG+=force_debug_info CONFIG+=sanitize_undefined CONFIG+=sanitizer"
  - os: linux
    services: docker
    sudo: required
    env: CONFIG=debug VERA=true TRANSLATIONS=true QMAKE_EXTRA="$QMAKE_EXTRA CONFIG+=sanitize_address CONFIG+=sanitize_undefined CONFIG+=sanitizer"
    name: Linux debug + vera + translations
  - os: osx
    language: cpp
    name: macOS release
    env: QMAKE_EXTRA="$QMAKE_EXTRA CONFIG+=sanitize_address CONFIG+=sanitize_undefined CONFIG+=sanitizer CONFIG+=force_debug_info"

before_install:
- wait $EARLY_START_DOCKER_PULL_PID || true
- if [[ $TRAVIS_OS_NAME  == osx ]] ; then [[ -n ${TRIK_PYTHON3_VERSION_MINOR:-} ]] || export TRIK_PYTHON3_VERSION_MINOR="$(python3 -V | sed 's#^Python [0-9]\.\([0-9]\)\.[0-9]*$#\1#g')" ; fi

install:
- "./scripts/install.sh"

script:
- ./scripts/script.sh & WPID=$!
- sleep 2400 && { kill $WPID || true ; echo "***KILLED ON TIMEOUT***" ; } & KPID=$!
- wait $WPID ; RES=$?; kill $KPID > /dev/null ; ( exit $RES )

after_script:
- "./scripts/after_script.sh"
- kill $HEARTBEAT

after_success:
- if [ "$CONFIG" = "debug" ]; then codecov; fi

notifications:
  slack:
    secure: KQUsvDU5DOVz8iP9V4L1O6GW02rPK6vavMi892aXnCIa5fRX+/hiwFQH4fHfFCDVpu93dtaVwfYKXgSQnjcC6foZSARbE4H6dTzU3TRgzwx8BMNJPlzkldFH+oYgctdvt/x9X04tatj1vj1hAEfFXL0QX6BYLeUsTj+AS+MZmck=
