FROM ubuntu:xenial
MAINTAINER jake.kirilenko@gmail.com
RUN apt update
RUN apt -y full-upgrade
RUN apt install -y build-essential vim-nox vim-scripts grep rsync pkg-config
# PythonQt & trik-runtime build dependencies
RUN apt install -y python3-dev qt5-default qtmultimedia5-dev qtscript5-dev qtbase5-private-dev
#trik-studio dependencies
RUN apt install -y libusb-1.0-0-dev libqt5svg5-dev qttools5-dev-tools
ENV HOME build
RUN mkdir $HOME
WORKDIR ${HOME}
